# Generated by Django 3.2.12 on 2024-08-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
